In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
# Importing the dataset
dataframe = pd.read_csv('pima-indians-diabetes.csv')
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [6]:
dataframe.shape

(768, 9)

In [11]:
# Divide Data into X and Y
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [12]:
################# Hold Out Validation #################
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [14]:
# Split the data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=7)
model = LogisticRegression()
model.fit(X_train, Y_train)
result = model.score(X_test, Y_test)
result

0.7559055118110236

In [16]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred

array([0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 1.

In [7]:
# Checking accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_pred)

0.7559055118110236

In [8]:
# Check the accuracy
print("Accuracy: ", result*100.0)

Accuracy:  75.59055118110236


In [9]:
### Realtime predictions
Real_predictions = model.predict([[1,2,3,4,5,6,7,8]])
Real_predictions

array([1.])

In [17]:
################# K Fold Validation #################

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [18]:
# Initialize parameters
num_folds = 10
seed = 7
kfold = KFold(n_splits=num_folds, random_state=seed)
model1 = LogisticRegression()

In [20]:
# Fitting the model and Extracting the results
results1 = cross_val_score(model1, X, Y, cv=kfold)
results1

array([0.7012987 , 0.81818182, 0.74025974, 0.71428571, 0.77922078,
       0.75324675, 0.85714286, 0.80519481, 0.72368421, 0.80263158])

In [23]:
# Check the accuracy
print("Accuracy: ", results1*100.0)
print ('\n\n')
print("mean of accuracy", results1.mean()*100.0)
print ("std.deviation of accuracies", results1.std()*100.0)

Accuracy:  [70.12987013 81.81818182 74.02597403 71.42857143 77.92207792 75.32467532
 85.71428571 80.51948052 72.36842105 80.26315789]



mean of accuracy 76.95146958304852
std.deviation of accuracies 4.841051924567195


In [24]:
################# Leave One Out Cross Validation #################

from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [25]:
# Initialize parameters
loocv = LeaveOneOut()
model2 = LogisticRegression()

In [28]:
# Fitting the model and Extracting the results
results2 = cross_val_score(model2, X, Y, cv=loocv)
len(results2)

768

In [29]:
# Check the Accuracy
print("Accuracy: ", results2*100.0)
print(results2.mean()*100.0)

Accuracy:  [100. 100. 100. 100. 100. 100.   0.   0. 100.   0. 100. 100.   0. 100.
 100. 100.   0.   0. 100.   0. 100. 100. 100.   0. 100.   0. 100. 100.
   0. 100. 100. 100. 100. 100. 100. 100.   0.   0.   0.   0.   0.   0.
 100. 100.   0. 100. 100. 100.   0. 100. 100. 100. 100. 100.   0. 100.
 100. 100.   0. 100. 100. 100. 100. 100.   0. 100.   0. 100. 100. 100.
   0. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100.   0. 100. 100. 100. 100. 100. 100.   0. 100.   0. 100. 100.
 100.   0. 100. 100. 100. 100. 100. 100. 100. 100. 100.   0. 100. 100.
 100. 100. 100.   0.   0. 100. 100. 100. 100. 100. 100. 100.   0.   0.
 100. 100.   0.   0. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100.   0.   0. 100. 100. 100.   0. 100. 100. 100. 100.   0.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.   0.   0. 100. 100.
 100. 100.   0. 100. 100. 100. 100. 100. 100. 100.   0. 100. 100. 100.
 100. 100. 100. 100. 100.   0.   0.   0. 100. 100. 100. 100. 100. 

In [30]:
################# Repeated K Fold Cross Validation ################# 

from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [31]:
# Initialize parameters
n_splits = 10
test_size = 0.33
seed = 7
kfold3 = ShuffleSplit(n_splits=n_splits, test_size=test_size, random_state=seed)
model3 = LogisticRegression()

In [32]:
# Fitting the model and Extracting the results
results3 = cross_val_score(model3, X, Y, cv=kfold3)
results3

array([0.75590551, 0.7519685 , 0.78346457, 0.76771654, 0.76377953,
       0.78346457, 0.7519685 , 0.79527559, 0.76377953, 0.73622047])

In [34]:
# Check the Accuracy
print("Accuracy: ", results3*100.0)
print ('\n\n')
print('mean of Accuracy', results3.mean()*100.0, results3.std()*100.0)

Accuracy:  [75.59055118 75.19685039 78.34645669 76.77165354 76.37795276 78.34645669
 75.19685039 79.52755906 76.37795276 73.62204724]



76.53543307086613 1.690622878234953
